development:
  secret_token: <%= ENV['SECRET_TOKEN_KEY_BASE'] %>
  secret_key_base: <%= ENV['SECRET_TOKEN_KEY_BASE'] %>

test:
  secret_token: <%= ENV['SECRET_TOKEN_KEY_BASE'] %>
  secret_key_base: <%= ENV['SECRET_TOKEN_KEY_BASE'] %>

production:
  secret_token: <%= ENV['SECRET_TOKEN_KEY_BASE'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
