development:
  secret_token: "development"
  secret_key_base: "development"

test:
  secret_token: "development"
  secret_key_base: "development"

production:
  secret_token: "development"
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
